### ISSUE TITLE
Add colors

### ISSUE THREAD

**Issue by jacopofar** [jacopofar/choose-activity#2]
It would be nice to have ANSI colors in the output, but ideally the tool should have no dependencies and work smoothly in old/weird terminals, by falling back to non-colored output

**Comment by ecthompson99** [comment]
Hey @jacopofar, I'm interested in trying this out! What are you specifically looking for in the output? Do you want random ANSI color output just to make it more colorful, or did you want to assign each activity/weight with a specific color?

**Comment by jacopofar** [comment]
Hello and thanks for the interest!
I was thinking about different colors to make it nicer, and easier to have a glance (e.g. a color for the list and a different color for the list of tasks.
Now that you mention it having different colors for different weights can be nice, still is probably tricky because there is no upper bound for the weight

**Comment by jacopofar** [comment]
Solved in #4
